# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: evergreen
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: hello-serverlles
# "service" is the name of this project. This will also be added to your AWS resource names.
service: hello-servelles

provider:
  name: aws
  runtime: nodejs20.x

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /hello
          method: get
